# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\IM@S2-Viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IMAS2ToolMainWindow(object):
    def setupUi(self, IMAS2ToolMainWindow):
        IMAS2ToolMainWindow.setObjectName("IMAS2ToolMainWindow")
        IMAS2ToolMainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(IMAS2ToolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        IMAS2ToolMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IMAS2ToolMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuConvert = QtWidgets.QMenu(self.menubar)
        self.menuConvert.setObjectName("menuConvert")
        self.menuConvert_scb = QtWidgets.QMenu(self.menuConvert)
        self.menuConvert_scb.setObjectName("menuConvert_scb")
        self.menuConvert_xmb = QtWidgets.QMenu(self.menuConvert)
        self.menuConvert_xmb.setObjectName("menuConvert_xmb")
        self.menuConvert_dds = QtWidgets.QMenu(self.menuConvert)
        self.menuConvert_dds.setObjectName("menuConvert_dds")
        IMAS2ToolMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IMAS2ToolMainWindow)
        self.statusbar.setObjectName("statusbar")
        IMAS2ToolMainWindow.setStatusBar(self.statusbar)
        self.actionOpen_mpc = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionOpen_mpc.setObjectName("actionOpen_mpc")
        self.actionOpen_tsk = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionOpen_tsk.setObjectName("actionOpen_tsk")
        self.actionOpen_nut = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionOpen_nut.setObjectName("actionOpen_nut")
        self.actionscb_to_json = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionscb_to_json.setObjectName("actionscb_to_json")
        self.actionjson_to_scb = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionjson_to_scb.setObjectName("actionjson_to_scb")
        self.actionxmb_to_json = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionxmb_to_json.setObjectName("actionxmb_to_json")
        self.actionjson_to_xmb = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionjson_to_xmb.setObjectName("actionjson_to_xmb")
        self.actionpng_to_dxt3dds = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actionpng_to_dxt3dds.setObjectName("actionpng_to_dxt3dds")
        self.actiondxt3dds_to_png = QtWidgets.QAction(IMAS2ToolMainWindow)
        self.actiondxt3dds_to_png.setObjectName("actiondxt3dds_to_png")
        self.menuOpen.addAction(self.actionOpen_mpc)
        self.menuOpen.addAction(self.actionOpen_tsk)
        self.menuOpen.addAction(self.actionOpen_nut)
        self.menuConvert_scb.addAction(self.actionscb_to_json)
        self.menuConvert_scb.addAction(self.actionjson_to_scb)
        self.menuConvert_xmb.addAction(self.actionxmb_to_json)
        self.menuConvert_xmb.addAction(self.actionjson_to_xmb)
        self.menuConvert_dds.addAction(self.actionpng_to_dxt3dds)
        self.menuConvert_dds.addAction(self.actiondxt3dds_to_png)
        self.menuConvert.addAction(self.menuConvert_scb.menuAction())
        self.menuConvert.addAction(self.menuConvert_xmb.menuAction())
        self.menuConvert.addAction(self.menuConvert_dds.menuAction())
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuConvert.menuAction())

        self.retranslateUi(IMAS2ToolMainWindow)
        QtCore.QMetaObject.connectSlotsByName(IMAS2ToolMainWindow)

    def retranslateUi(self, IMAS2ToolMainWindow):
        _translate = QtCore.QCoreApplication.translate
        IMAS2ToolMainWindow.setWindowTitle(_translate("IMAS2ToolMainWindow", "IM@S2-Viewer"))
        self.menuOpen.setTitle(_translate("IMAS2ToolMainWindow", "Open"))
        self.menuConvert.setTitle(_translate("IMAS2ToolMainWindow", "Convert"))
        self.menuConvert_scb.setTitle(_translate("IMAS2ToolMainWindow", "Convert scb"))
        self.menuConvert_xmb.setTitle(_translate("IMAS2ToolMainWindow", "Convert xmb"))
        self.menuConvert_dds.setTitle(_translate("IMAS2ToolMainWindow", "Convert dds"))
        self.actionOpen_mpc.setText(_translate("IMAS2ToolMainWindow", "Open mpc"))
        self.actionOpen_tsk.setText(_translate("IMAS2ToolMainWindow", "Open tsk"))
        self.actionOpen_nut.setText(_translate("IMAS2ToolMainWindow", "Open nut"))
        self.actionscb_to_json.setText(_translate("IMAS2ToolMainWindow", "scb to json"))
        self.actionjson_to_scb.setText(_translate("IMAS2ToolMainWindow", "json to scb"))
        self.actionxmb_to_json.setText(_translate("IMAS2ToolMainWindow", "xmb to json"))
        self.actionjson_to_xmb.setText(_translate("IMAS2ToolMainWindow", "json to xmb"))
        self.actionpng_to_dxt3dds.setText(_translate("IMAS2ToolMainWindow", "png to dxt3dds"))
        self.actiondxt3dds_to_png.setText(_translate("IMAS2ToolMainWindow", "dxt3dds to png"))
